### PR TITLE
front: css: use a real default font

### PR DESCRIPTION
**Pull request by LeoColomb**
Maybe you like serif for description, but since you load Roboto, it's quite heretic, isn't it? :smiley:

| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by yanndinendal** [comment]
:+1:

**Comment by MoiTux** [comment]
Ok but you should clean [this file](https://github.com/Gandi/baobab/blob/master/baobab.front/less/event.less) by removing the 'font-family' since it will be useless

**Comment by LeoColomb** [comment]
@MoiTux Done! :smile: 
BTW, your styles are hard to read, you should consider using at least a linter, shouldn't you?

**Comment by MoiTux** [comment]
@LeoColomb Thanks
Yes you probably right, I'll talked about it with my coworkers who knows 'css' much better than me

**Pull request merged**
